#!/usr/bin/env python
# This is a non-functional "quantifier" that
# mimic something like the flux capacitor

import argparse
import logging
import sys
import os

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format='[%(levelname)s] : %(message)s')

    parser = argparse.ArgumentParser(prog="quantifier", description="""
    Quantify a set of alignments
    """)
    parser.add_argument("-i", "--input", help="Input file")
    parser.add_argument("-o", "--output", help="Output file")
    parser.add_argument("--annotation", help="The genome annotation", required=True)
    parser.add_argument("--fail", help="Trigger a failure", action="store_true", default=False)
    parser.add_argument("--log", help="Set the log level",
                        choices=["DEBUG", "INFO", "WARN", "ERROR"],
                        default="ERROR")

    args = parser.parse_args()
    # set log level
    logging.getLogger().setLevel(
        {
            "ERROR": logging.ERROR,
            "WARN": logging.WARNING,
            "INFO": logging.INFO,
            "DEBUG": logging.DEBUG
        }[args.log]
    )

    # do some checks
    if args.fail:
        logging.error("Fail requested")
        sys.exit(1)

    if not os.path.exists(args.annotation):
        logging.error("File not found : %s" % args.annotation)
        sys.exit(1)

    logging.info("Starting the quantification")


    in_file = sys.stdin
    if args.input is not None:
        in_file = open(args.input, "r")

    counts = {}
    for line in in_file:
        reads = [s.split("::") for s in line.strip().split("\t")[3].split(",")]
        for name in [r.split(":")[0] for pair in reads for r in pair]:
            counts[name] = counts.get(name, 0) + 1

    if args.input is not None:
        in_file.close()

    f = sys.stdout
    if args.output is not None:
        f = open(args.output, "w")

    for name, count in counts.items():
        f.write("%s\t%d\n" % (name, count))

    if args.output is not None:
        f.close()

    logging.info("Done :)")
